### ISSUE TITLE
on_stop not called on Android

### ISSUE THREAD

**Issue by brvier** [kivy/python-for-android#1226]
By adding some logs it s look like SDLActivity.mSDLThread.join(); never ends.

So apps isn t really close and can t be bring to front by a service or can t be launch again.

if i comment this part in bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLActivity.java, the app is well destroyed :

```
          // Now wait for the SDL thread to quit
          if (SDLActivity.mSDLThread != null) {
              try {
                  SDLActivity.mSDLThread.join();
              } catch(Exception e) {
                  Log.v("SDL", "Problem stopping thread: " + e);
              }
              SDLActivity.mSDLThread = null;
  
              Log.v("SDL", "Finished waiting for SDL thread");
          }
```

**Comment by inclement** [comment]
Just confirmed on_stop is being called now. This was probably fixed by https://github.com/kivy/python-for-android/pull/1528 even if not beforehand, with the explicit sys.exit call.

**Comment by brvier** [comment]
I'll try to test this new SDL build shortly, mainly for text improvement, but look like i need to use also switch to kivy master for a orientation bug, and to switch to master i need to rewrite some part as some deprecated things have been removed :)

**Comment by brvier** [comment]
Unfortunatly, while mSDLThread stop now, the on_stop is still not called on master.
