### ISSUE TITLE
str.decode() issue again for Python 3

### ISSUE THREAD

**Issue by chippyash** [kivy/python-for-android#1749]
### Versions

* Python: 3.7
* OS: Ubuntu 18.04
* Kivy: current stable
* Cython: 0.29.6

### Description

This is very similar to https://github.com/kivy/buildozer/issues/756 which turned out to be a python-for-android issue

L178 of .buildozer/android/platform/python-for-android/pythonforandroid/recipes/android/src/android/_android.pyx

has 
```
python_act = autoclass(JAVA_NAMESPACE.decode('utf8') + u'.PythonActivity')
```

I changed it to 
```
python_act = autoclass(JAVA_NAMESPACE + u'.PythonActivity')
```
did a buildozer clean, then built and deployed again and it worked.

So, as per original ticket, there are other places that need to be cleaned up perhaps for Python 3.

Command:
```sh
 buildozer android debug deploy
```

**Comment by darosior** [comment]
+1, I did a PR for this yesterday

**Comment by homdx** [comment]
Hello.
Maybe it's some error:
(my test repo) build based by @JonasT p4a-build-spaces
https://github.com/homdx/flask-hello
log from phone
```
I/python  (29860): Android kivy bootstrap done. __name__ is __main__
I/python  (29860): AND: Ran string
I/python  (29860): Run user program, change dir and execute entrypoint
I/python  (29860): [INFO   ] [Logger      ] Record log in /data/data/com.example.test1/files/app/.kivy/logs/kivy_19-03-13_1.txt
I/python  (29860): [INFO   ] [Kivy        ] v1.11.0.dev0, git-Unknown, 20190313
I/python  (29860): [INFO   ] [Python      ] v3.7.1 (default, Mar 13 2019, 07:18:03) 
I/python  (29860): [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
I/python  (29860): [INFO   ] [Factory     ] 184 symbols loaded
I/python  (29860): [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
I/python  (29860): [INFO   ] [Text        ] Provider: sdl2
I/python  (29860): Starting Flask app...
I/python  (29860): [INFO   ] [Window      ] Provider: sdl2
I/python  (29860): [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
I/python  (29860): [INFO   ] [GL          ] Backend used <sdl2>
I/python  (29860): [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.1 build 1.4@3300288'>
I/python  (29860): [INFO   ] [GL          ] OpenGL vendor <b'Imagination Technologies'>
I/python  (29860): [INFO   ] [GL          ] OpenGL renderer <b'PowerVR Rogue G6200'>
I/python  (29860): [INFO   ] [GL          ] OpenGL parsed version: 3, 1
I/python  (29860): [INFO   ] [GL          ] Texture max size <8192>
I/python  (29860): [INFO   ] [GL          ] Texture max units <16>
I/python  (29860): [INFO   ] [Window      ] auto add sdl2 input provider
I/python  (29860): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
I/python  (29860): [WARNING] [Base        ] Unknown <android> provider
I/python  (29860): [INFO   ] [Base        ] Start application main loop
I/python  (29860): [INFO   ] [GL          ] NPOT texture support is available
I/python  (29860): [INFO   ] [Base        ] Leaving application in progress...
I/python  (29860):  Traceback (most recent call last):
I/python  (29860):    File "/home/userhome/flask-hello/main.py", line 28, in <module>
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/app.py", line 855, in run
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/base.py", line 502, in runTouchApp
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/core/window/window_sdl2.py", line 724, in mainloop
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/core/window/window_sdl2.py", line 459, in _mainloop
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/base.py", line 337, in idle
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/clock.py", line 581, in tick
I/python  (29860):    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
I/python  (29860):    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
I/python  (29860):    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
I/python  (29860):    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/kivy/base.py", line 208, in remove_android_splash
I/python  (29860):    File "/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/android/__init__.py", line 8, in <module>
I/python  (29860):    File "android/_android.pyx", line 178, in init android._android
I/python  (29860):  AttributeError: 'str' object has no attribute 'decode'
I/python  (29860): Python for android ended.
```

**Comment by JonasT** [comment]
Maybe you still got an older version of `p4a`? You could try the p4a build spaces option `--force-redownload-p4a` or alternatively cleaning the Docker image. (without that option `p4aspaces` will per default let docker **cache**/not redownload p4a unless required, so you can work offline with previously launched environments)

**Comment by homdx** [comment]
@JonasT hello)) No. If compile today and give are black screen at kivy app . You can reproduce with my repo (link upper)

**Comment by homdx** [comment]
@chippyash
It's is realy help!
```
Fix android/pythonforandroid/recipes/android/src/android/_android.pyx

has

python_act = autoclass(JAVA_NAMESPACE.decode('utf8') + u'.PythonActivity')
I changed it to

python_act = autoclass(JAVA_NAMESPACE + u'.PythonActivity')

```

**Comment by AndreMiras** [comment]
Thanks for the report. This was fixed recently with https://github.com/kivy/python-for-android/pull/1748 and https://github.com/kivy/python-for-android/pull/1752
You need to update to master

**Comment by SmartWaddles** [comment]
> Thanks for the report. This was fixed recently with #1748 and #1752
> You need to update to master

Hello there!
Fix with removing `.decode()` from `python_act` didn't solve the problem for me.
After I found via adb, that my apk crashes on startup with an error `File "android/_android.pyx", line 178, in init android._android AttributeError: 'str' object has no attribute 'decode'` , I've tried to delete `.decode('utf-8')` manually from _android.pyx source. 
I've changed
`python_act = autoclass(JAVA_NAMESPACE.decode('utf8') + u'.PythonActivity')` to
`python_act = autoclass(JAVA_NAMESPACE + u'.PythonActivity')` but after that I've faced an error `TypeError: must be str, not bytes` at the same place. 
So I've decided to wrap up JAVA_NAMESPACE to string:
`python_act = autoclass(str(JAVA_NAMESPACE) + u'.PythonActivity')`  but after that I've got:
`jnius.jnius.JavaException: Class not found b"b'org/kivy/android'/PythonActivity"`. Finally, I've just hardcoded this path instead of JAVA_NAMESPACE and voila, APK was launched successfully.
Should I change this path somewhere else instead of hardcoding it there? Or my fix is OK?
I just don't want to re-upload all the recipes and building tools - i think it will be necessary if I'll re-install p4a.

Sorry, I'm a little new here.

**Comment by JonasT** [comment]
@AndreMiras  shouldn't it either be `PythonActivity` without the `u` that forces a unicode string (so it's bytes/str on python 2 as normal, and unicode/str on python 3 as normal), or alternatively pyjnius changed to return uniformly always bytes (even under python 3) or always unicode (even under python 2)?

Seems the main issue is here that the `u` prefix assumes a uniform return type when there just isn't one, so either that `u` prefix or the current pyjnius behavior don't make sense

**Comment by JonasT** [comment]
@SmartWaddles I just checked, the latest master has no decode on this line you could remove. Also, `JAVA_NAMESPACE` should already be unicode from what I could see. Do you use an older version? It might work fine if you just go to latest master instead of trying to fix this manually

**Comment by SmartWaddles** [comment]
> @SmartWaddles I just checked, the latest master has no decode on this line you could remove. Also, `JAVA_NAMESPACE` should already be unicode from what I could see (on master). Do you use an older version? It might work fine if you just go to latest master instead of trying to fix this manually

Yes, I've used and older version. I fixed it manually successfully, thanks.
